// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserResponse struct {
	ID string `json:"id"`
}

type LoginUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginUserResponse struct {
	ID    string `json:"id"`
	Token string `json:"token"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	IsAdmin  bool   `json:"isAdmin"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
